import os

PAYMENT_MAIN_BOT_KEY = os.getenv('PAYMENT_MAIN_BOT_KEY', '')
PAYMENT_PREFIX = os.getenv('PAYMENT_PREFIX', '!')
PAYMENT_UPI_ID = os.getenv('PAYMENT_UPI_ID', '')
PAYMENT_BUSINESS_NAME = os.getenv('PAYMENT_BUSINESS_NAME', '')
PAYMENT_NOTE = os.getenv('PAYMENT_NOTE', 'Payment request')
PAYMENT_RECEIPT_FOOTER = os.getenv('PAYMENT_RECEIPT_FOOTER', 'Requested by')
PAYMENT_GUILD_ID = os.getenv('PAYMENT_GUILD_ID', '0')
PAYMENT_APP_ID = os.getenv('PAYMENT_APP_ID', '0')
PAYMENT_ALLOWED_USER_IDS = os.getenv('PAYMENT_ALLOWED_USER_IDS', '')
PAYMENT_COLOR = os.getenv('PAYMENT_COLOR', '0x00c8ff')
PAYMENT_PAID_COLOR = os.getenv('PAYMENT_PAID_COLOR', '0x23a55a')
